print("Escape sequences:")
print()
print("Type Description")
print("‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾")
print("\\a\t|Bell (alert)")
print("\\b\t|Backspace")
print("\\n\t|New line")
print("\\t\t|Horizontal tab")
print("\\ \t|Backslash")
print("\\\"\t|Double quotation mark  “")
print("\\\'\t|Single quotation mark ‘")
